spring.application.name=sgsapi

spring.datasource.url= jdbc:postgresql://localhost:5432/mabbix_db
spring.datasource.username=postgres

spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

security.jwt.expiracao=30
security.jwt.chave-assinatura=VW0gc2VncmVkbyBtdWl0byBsb25nbyBwYXJhIGFzc2luYXIgbyB0b2tlbiBKV1QgZGEgc29ydmV0ZXJpYSBTR1MP